# quiet load libraries
# suppressPackageStartupMessages(library(tidyverse))
# suppressPackageStartupMessages(library(rattle))
# suppressPackageStartupMessages(library(Hmisc))
# suppressPackageStartupMessages(library(corrgram))
# suppressPackageStartupMessages(library(caret))
# suppressPackageStartupMessages(library(gridExtra))
# suppressPackageStartupMessages(library(adabag))
# suppressPackageStartupMessages(library(fastAdaboost))
# suppressPackageStartupMessages(library(rlist))

library(tidyverse)
library(rattle)
library(Hmisc)
library(corrgram)
library(caret)
library(gridExtra)
library(adabag)
library(fastAdaboost)
library(rlist)
